#105 : Apresenta imagem por palavra
fga-eps-mds/2021.1-Multilind-Mobile-App pull request #13
Opened 2021-10-01 20:32 UTC by CarlosZoft

## Description

Nesta issue, foi adicionado a tela de images relacionadas com palavras.

## Solve (Issue)
#105

## Tasks
- [x] Conectar front com o banco de imagens
- [x] Fazer tela de Imagens de uma língua em ordem alfabética

## Acceptance Criteria  
- [x] Ordem alfabética

## Assets

![Screenshot from 2021-10-01 17-27-04](https://user-images.githubusercontent.com/62192072/135682764-f61b707e-2ce7-4356-be20-7ff12978c9c3.png)

2021-10-02 02:05 UTC, pedroeagle requested changes
Quando seleciono a língua Arauá não há imagens disponíveis. Quando seleciono uma língua que possui imagens as imagens não estão sendo mostradas.

2021-10-02 13:36 UTC, pedroeagle approved these changes

2021-10-02 13:52 UTC, sofiapatrocinio approved these changes

2021-10-03 16:37 UTC, micaellagouveia approved these changes

2021-10-03 16:37 UTC, merged