100 languages
fga-eps-mds/2021.1-Multilind-Mobile-App pull request #5
Opened 2021-09-15 19:24 UTC by isadoragalvaoss

2021-09-15 19:33 UTC, pedroeagle reviewed
Remove os arquivos package-lock.json e o yarn.lock do PR

2021-09-15 23:10 UTC, GabrielDVpereira requested changes
os pull requests de desenvolvimento devem ser abertos para o branch devel e não para a main

2021-09-16 00:40 UTC, sofiapatrocinio commented
Só corrigir esses dois erros de lint:
Error:   1:17  error  'useState' is defined but never used   no-unused-vars
Error:   1:27  error  'useEffect' is defined but never used  no-unused-vars

2021-09-16 00:40 UTC, sofiapatrocinio requested changes
Só corrigir esses dois erros de lint:
Error:   1:17  error  'useState' is defined but never used   no-unused-vars
Error:   1:27  error  'useEffect' is defined but never used  no-unused-vars

2021-09-17 00:12 UTC, closed without merging