100 languages screen
fga-eps-mds/2021.1-Multilind-Mobile-App pull request #7
Opened 2021-09-18 00:07 UTC by isadoragalvaoss

## Description

Create the language screen

## Solve(Issue )
Resolve #100 

## Tasks done with this PR
- [x] Language list screen
- [x] Language home page

## Critérios de aceitação 
- [x] List all languages
- [ ] List by alphabetical order

## Assets

![image](https://user-images.githubusercontent.com/54413452/133864933-00a335a4-8c4a-449d-a3a4-3bdf05bf292d.png)
![image](https://user-images.githubusercontent.com/54413452/133864945-a79fb013-6457-4a6a-ae22-61b8397a99ce.png)

2021-09-20 19:53 UTC, micaellagouveia submitted a review, later dismissed
Arrasaram galeraa!!

2021-09-20 23:51 UTC, GabrielDVpereira requested changes
just move the styles to a style file and fix the things pointed out

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageInitialScreen/index.jsx
> +  const dicionary = require('../../assets/images/dicionary.png');
Please put this import outside the component and use import instead of require

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageInitialScreen/index.jsx
> +        style={{ position: 'absolute', top: 55, left: 15 }}
move this style to another style file

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageInitialScreen/index.jsx
> +          fontFamily: MONTSERRAT_BOLD,
move this style to another style file

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageInitialScreen/index.jsx
> +      <View style={{ width: 363, top: 50 }}>
move this style to another style file

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageInitialScreen/index.jsx
> +            fontFamily: MONTSERRAT_REGULAR,
move this style to another style file

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageScreen/index.jsx
> +            style={{
move this style to another style file

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageScreen/index.jsx
> +  const [lista, setLista] = useState(languages);
change the name of the variable to English

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageScreen/index.jsx
> +  const listOrdenada = () => {
change the name of the variable to English

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageScreen/index.jsx
> +  const listDesOrdenada = () => {
change the name of the variable to English

2021-09-20 23:51 UTC, GabrielDVpereira commented on src/screens/LanguageScreen/index.jsx
> +  const listOrdenadaTronco = () => {
change the name of the variable to English

2021-09-21 00:22 UTC, sofiapatrocinio requested changes
O botão de filtro tá desalinhado com o input:
![photo5064390325094689219](https://user-images.githubusercontent.com/38709421/134093687-7bc3fd2e-fe4b-4e76-8ce0-92570f07de73.jpg)

O modal de filtro tá cortado e quando clico fora ele não fecha:
![photo5064390325094689218](https://user-images.githubusercontent.com/38709421/134093752-6e6d6eb9-27e9-4da6-9275-9b180d0f3580.jpg)

Falta padding na esquerda, antes do texto e margem acima da barra de porcentagem:
![photo5064390325094689220](https://user-images.githubusercontent.com/38709421/134093789-d376178c-91d3-4984-92d7-aba4e13690a4.jpg)

Meu celular é o Iphone 7

2021-09-22 17:38 UTC, micaellagouveia approved these changes

2021-09-22 21:48 UTC, sofiapatrocinio requested changes

2021-09-22 21:48 UTC, sofiapatrocinio commented on src/screens/LanguageInitialScreen/styles.js
> +    paddingLeft: 29,
Vai precisar de um paddingRight tbm
![image](https://user-images.githubusercontent.com/38709421/134424280-a21849f7-b9c0-48aa-ac11-e7d669507ede.png)

2021-09-22 21:48 UTC, sofiapatrocinio commented on src/screens/LanguageScreen/index.jsx
> +              style={{ left: 350 }}
O filtro tá muito a esquerda e pode diminuir a margem acima tbm 
![image](https://user-images.githubusercontent.com/38709421/134426176-9fd23dc9-fd31-4698-822b-d8c1841436a7.png)

2021-09-22 21:48 UTC, sofiapatrocinio commented on src/screens/LanguageScreen/index.jsx
> +        <ScrollView style={{ top: 50 }}>{list()}</ScrollView>
Acho que a margem superior pode ser de 20, só precisa mostrar o input mesmo

2021-09-22 21:48 UTC, sofiapatrocinio commented on src/screens/LanguageScreen/index.jsx
> +                  Listar por nome (decrescente)
Não tá mais ordenando de forma decrescente

https://user-images.githubusercontent.com/38709421/134426596-92f55d94-bca9-4519-b678-b73b23c07dae.MP4

2021-09-22 22:55 UTC, sofiapatrocinio approved these changes

2021-09-23 18:20 UTC, sofiapatrocinio approved these changes

2021-09-23 18:35 UTC, micaellagouveia approved these changes

2021-09-24 00:41 UTC, GabrielDVpereira requested changes

2021-09-24 00:41 UTC, GabrielDVpereira commented on App.js
> +  Linguas();
I should not be called inside the main

2021-09-24 20:35 UTC, micaellagouveia approved these changes

2021-09-25 12:47 UTC, sofiapatrocinio approved these changes

2021-09-25 23:08 UTC, GabrielDVpereira approved these changes

2021-09-25 23:08 UTC, merged