#100 list languages
fga-eps-mds/2021.1-Multilind-Mobile-App pull request #8
Opened 2021-09-23 22:37 UTC by hericklima22

Connected the languages list with the back end.

2021-09-24 00:48 UTC, GabrielDVpereira requested changes
Just check why the pipeline is breaking and check if this branch is up to date to the branch 100-languages, I think you created this branch from it, but I think it's not up to date.

2021-09-24 00:48 UTC, GabrielDVpereira commented on src/screens/LanguageScreen/index.jsx
> +  // console.log('####################', list());
remove this comment

2021-09-24 00:48 UTC, GabrielDVpereira commented on src/screens/LanguageScreen/index.jsx
> +// import Languages from '../../languages.json';
remove this commment

2021-09-24 20:39 UTC, sofiapatrocinio approved these changes

2021-09-25 23:09 UTC, GabrielDVpereira approved these changes

2021-09-25 23:09 UTC, merged